# Generated by Django 3.2.9 on 2021-11-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.IntegerField(max_length=100)),
                ('avaliacao', models.IntegerField(max_length=4)),
            ],
        ),
    ]
